version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - eda-network
    depends_on:
      - db
      - rabbitmq
  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - eda-network
    depends_on:
      - rabbitmq
      - user-service
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=eda_notifications_users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./eda-data:/var/lib/postgresql/data
    networks:
      - eda-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      - eda-network

networks:
  eda-network:
    driver: bridge

volumes:
  eda-data: